FROM node:20.10.0

WORKDIR /app

RUN apt-get update && apt-get install -y curl unzip

COPY ./scripts/webapps.sh /app

COPY ./.env /app

RUN chmod +x /app/webapps.sh

RUN /app/webapps.sh


CMD ["exit", "0"]

