# Use the official PostgreSQL image as the base image
FROM postgres:12.14-alpine

# Set environment variables for PostgreSQL
ENV POSTGRES_DB=dhis2 \
    POSTGRES_USER=dhis \
    POSTGRES_PASSWORD=dhis

# Expose port 5432
EXPOSE 5432/tcp

# Set the working directory to PostgreSQL's data directory
WORKDIR /var/lib/postgresql/data