# Use the official Nginx image as the base image
FROM nginx:1.23.3-alpine

# Copy Nginx configuration file to the container
COPY /root/.cache/d2/cache/clusters/2.38.0/docker-compose/cluster/config/nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80/tcp

# Set the working directory to the Nginx directory
WORKDIR /app