# Use the official OpenJDK image as the base image
FROM openjdk:11.0.16

# Copy the JAR file to the container
COPY target/InternationalInstance.jar /international_javabackend/

# Set additional environment variables
ENV PATH="/usr/local/openjdk-11/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
    JAVA_HOME="/usr/local/openjdk-11" \
    LANG="C.UTF-8" \
    JAVA_VERSION="11.0.16"

# Expose port 7009
EXPOSE 7009/tcp

# Set the working directory to the Java backend directory
WORKDIR /international_javabackend