# Use the official Tomcat image as the base image
FROM tomcat:9.0.62-jdk11-openjdk

# Set the DHIS2_HOME environment variable
ENV DHIS2_HOME=/DHIS2_home

# Copy the required files to the container
COPY /root/.cache/d2/cache/clusters/2.38.0/docker-compose/cluster/config/server.xml /usr/local/tomcat/conf/server.xml
COPY /root/.cache/d2/cache/clusters/2.38.0/docker-compose/cluster/config/DHIS2_home/dhis.conf /DHIS2_home/dhis.conf
COPY /root/.cache/d2/cache/clusters/2.38.0/docker-compose/cluster/config/DHIS2_home/log4j2.xml /DHIS2_home/log4j2.xml

# Set additional environment variables
ENV CATALINA_OPTS="-Dcontext.path='' -Dlog4j2.configurationFile=/DHIS2_home/log4j2.xml" \
    PATH="/usr/local/tomcat/bin:/usr/local/openjdk-11/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
    JAVA_HOME="/usr/local/openjdk-11" \
    LANG="C.UTF-8" \
    JAVA_VERSION="11.0.15" \
    CATALINA_HOME="/usr/local/tomcat" \
    TOMCAT_NATIVE_LIBDIR="/usr/local/tomcat/native-jni-lib" \
    LD_LIBRARY_PATH="/usr/local/tomcat/native-jni-lib" \
    GPG_KEYS="48F8E69F6390C9F25CFEDCD268248959359E722B A9C5DF4D22E99998D9875A5110C01C5A2F6059E7 DCFD35E0BF8CA7344752DE8B6FB21E8933C60243" \
    TOMCAT_MAJOR="9" \
    TOMCAT_VERSION="9.0.62" \
    TOMCAT_SHA512="179af1d50a7d330d0842d3f1cae086bbc1b20e8f6752d66500663f3ac71d80f50113bbd29931e21c8e2eccd982f9f872e193364311316fdd67349130d440c83f" \
    WAIT_FOR_DB_CONTAINER=""

# Expose port 8080
EXPOSE 8080/tcp

# Set the working directory to Tomcat's bin directory
WORKDIR /usr/local/tomcat
