# Use the official PostgreSQL image as the base image
FROM postgres:14.1-alpine

# Set environment variables for PostgreSQL
ENV POSTGRES_DB=international_db \
    POSTGRES_USER=postgres \
    POSTGRES_PASSWORD=postgres

# Expose port 5432
EXPOSE 5432/tcp

# Set the working directory to PostgreSQL's data directory
WORKDIR /var/lib/postgresql/data